export const BG    = "#f2f4f0";          // light sage-white background
export const CARD  = "#ffffff";          // white cards
export const CARD2 = "#eef0eb";          // very light green-gray
export const CREAM = "#1a1f1a";          // near-black text (was cream)
export const G     = "#1a6b3a";          // dark green accent (unchanged)
export const GO    = "#8a6a00";          // darker gold — readable on light bg
export const GOLD  = "#7a5c00";          // deep gold
export const M     = "#5a6b5c";          // muted green-gray (was pale)
export const R     = "#b02020";          // deeper red for contrast
export const FD    = "'Cormorant Garamond','Georgia',serif";
export const FB    = "'Inter','Helvetica Neue',sans-serif";
